# Generated by Django 2.2 on 2020-03-28 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_prfilefeeditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrfileFeedItem',
            new_name='ProfileFeedItem',
        ),
    ]
